### ISSUE TITLE
ConcurrentModificationException when finishing a class

### ISSUE THREAD

**Issue by shoaniki** [cojen/Maker#4]
I'm seeing an exception raised when I finish some classes:

    java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.cojen.maker@2.2.2/org.cojen.maker.TheClassMaker.finishTo(TheClassMaker.java:789)
	at org.cojen.maker@2.2.2/org.cojen.maker.TheClassMaker.finishBytes(TheClassMaker.java:742)
	at org.cojen.maker@2.2.2/org.cojen.maker.TheClassMaker.finishBytes(TheClassMaker.java:731)
	at [my code...]

The immediate cause is that something in `TheMethodMaker.doFinish` has added a new `<clinit>` entry to `mMethods`.  Here's a stack trace from the moment when that happens:

    org.cojen.maker.TheClassMaker.addClinit(TheClassMaker.java:367)
	at org.cojen.maker.TheMethodMaker.addExplicitConstantOp(TheMethodMaker.java:2400)
	at org.cojen.maker.TheMethodMaker.addExplicitConstantOp(TheMethodMaker.java:2367)
	at org.cojen.maker.TheMethodMaker$ConstantVar.pushTo(TheMethodMaker.java:4870)
	at org.cojen.maker.TheMethodMaker$ConstantVar.push(TheMethodMaker.java:4866)
	at org.cojen.maker.TheMethodMaker.doAddPushOp(TheMethodMaker.java:2260)
	at org.cojen.maker.TheMethodMaker.addPushOp(TheMethodMaker.java:1896)
	at org.cojen.maker.TheMethodMaker$OwnedVar.ifRelational(TheMethodMaker.java:3940)
	at org.cojen.maker.TheMethodMaker$OwnedVar$2.flow(TheMethodMaker.java:4211)
	at org.cojen.maker.TheMethodMaker$Flow.run(TheMethodMaker.java:2790)
	at org.cojen.maker.TheMethodMaker$BranchOp.flow(TheMethodMaker.java:3325)
	at org.cojen.maker.TheMethodMaker$Flow.run(TheMethodMaker.java:2790)
	at org.cojen.maker.TheMethodMaker$BranchOp.flow(TheMethodMaker.java:3325)
	at org.cojen.maker.TheMethodMaker$Flow.run(TheMethodMaker.java:2790)
	at org.cojen.maker.TheMethodMaker.doFinish(TheMethodMaker.java:189)
	at org.cojen.maker.TheClassMaker.finishTo(TheClassMaker.java:790)
	at org.cojen.maker.TheClassMaker.finishBytes(TheClassMaker.java:742)
	at org.cojen.maker.TheClassMaker.finishBytes(TheClassMaker.java:731)

This is in the JDK-8270928 workaround code. Presumably the creation of this static field is intended to have happened much earlier – I don't currently have any idea why it's being deferred until it's too late.

Unfortunately I can't currently share the actual code that's triggering it, and I haven't managed to reproduce the error yet in toy examples, but I figure I'll report it now anyway in case you have any ideas about how this would happen.

**Comment by broneill** [comment]
I can reproduce it by calling `Variable.eq` against a dynamic constant.

**Comment by shoaniki** [comment]
Aha, that's it -- I was doing `x.ifEq(y, label)` in my toy code, but now that I look at it I can see the real code that is breaking is indeed equivalent to `x.eq(y).ifTrue(label)` instead.

**Comment by broneill** [comment]
This should fix it: https://github.com/cojen/Maker/commit/a17b94219fe013d95d09d45d265a9f3eedcf92a8

**Comment by shoaniki** [comment]
Almost! This works provided the constant is assigned to a variable, but still fails if the constant is a Constable instance (e.g. in the test case, if instead of `mm.var(CondyTest.class).condy("boot").invoke(Object.class, "_")`, the constant is `new MagicConstant(1)`).

**Comment by broneill** [comment]
How about now? https://github.com/cojen/Maker/commit/6451625786eb5d39f67be2d1c62644ce7f34ffa3

**Comment by shoaniki** [comment]
Perfect, thank you!
